### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by rhmaaa** [Lin-Mao/DrGPUM#1]
when I run ./script/install.sh 80, there are some question

cat: gvprof-measurements/memory_liveness/memory_liveness.csv: No such file or directory
cp: cannot stat 'gvprof-measurements/memory_liveness/': No such file or directory
cat: gvprof-measurements/memory_liveness/memory_liveness.csv: No such file or directory
python: can't open file '/root/scripts/python/show_liveness_pattern.py': [Errno 2] No such file or directory

**Comment by Lin-Mao** [comment]
Hi @rhmaaa , `./script/install.sh 80` is the installation script. You can't generate `gvprof-measurements/` if you don't profile the applications.
