### ISSUE TITLE
torch_monitor.h: No such file or directory 

### ISSUE THREAD

**Issue by 1aureate** [Lin-Mao/DrGPUM#2]
I want to utilize DrGPUM for gpu memory optimization guidance following the readme and encounters this issue. 
```
src/analysis/memory_liveness.cpp:14:10: fatal error: torch_monitor.h: No such file or directory
   14 | #include "torch_monitor.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```
When i check the torch_monitor directory, i found it's empty because this submodule's github page has 404 error.
I guess this issue is relevant to the visibility of this submodule's repo, could someone help me with this? thanks a lot!

**Comment by Lin-Mao** [comment]
Hi @1aureate, we plan to do some work based on the torch-monitor so we closed it. Sorry for the inconvenience. I'll solve the dependency later.
As for now, you can download the torch-monitor from [here](https://doi.org/10.5281/zenodo.7588406) and replace the empty torch-monitor manually. If you have any trouble with the installation feel free to launch an issue.
